#!/bin/bash

CC=clang
CDEBUGFLAGS="-g -fstandalone-debug -D_GLIBCXX_DEBUG -DDEBUG"
CFLAGS="-Isrc -Imbed-crypto/include -DMBEDTLS_CONFIG_FILE=\"mbedtls-config.h\""

if [ "$2" = "debug" ]
then
  CFLAGS="$CFLAGS $CDEBUGFLAGS"
fi

SRC="src/buffer.c \
  src/fota.c"

LIB="mbed-crypto/library/rsa.c \
  mbed-crypto/library/bignum.c \
  mbed-crypto/library/md.c \
  mbed-crypto/library/oid.c \
  mbed-crypto/library/platform_util.c \
  mbed-crypto/library/rsa_internal.c \
  mbed-crypto/library/sha256.c \
  mbed-crypto/library/sha1.c \
  mbed-crypto/library/aes.c"

if [ "$1" = "client" ] || [ "$1" = "client-stripped" ]
then
  echo "Building fota $1 $2"
  SRC="$SRC src/fota-client.c"
  CFLAGS="-Os -m32 -DFOTA_CLIENT -DBUFFER_NO_STDIO $CFLAGS"
  OUTPUT=fota-client 
else
  echo "Building fota tool $2"
  SRC="$SRC src/fota-tool.c"
  CFLAGS="-O3 -DFOTA_TOOL $CFLAGS"
  OUTPUT=fota-tool
fi

$CC $CFLAGS $SRC $LIB -o $OUTPUT

if [ "$1" = "client-stripped" ]
then
  strip $OUTPUT
  echo -n "Size: "
  stat -c "%s" fota-client
fi
